blank_issues_enabled: true
contact_links:
  - name: Landscape feature request
    url: https://github.com/urbit/landscape/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=
    about: Landscape is comprised of Tlon's user applications and client for Urbit. Submit Landscape feature requests here.
  - name: urbit-dev mailing list
    url: https://groups.google.com/a/urbit.org/g/dev
    about: Developer questions and discussions also take place on the urbit-dev mailing list.